name: Northern Forest Canoe Trail
favicon: null
layout_spectrum: 0.9616004268173128
typography_spectrum: 0.6854012114927173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9235481256619096
  lightness: 0.5824547139927745
  saturation: 0.7056440878659487
  rhythmicContrast: 0.8981242864392698
purpose: []
